### ISSUE TITLE
Android release version on F-Droid

### ISSUE THREAD

**Issue by s4msung** [v4rakh/fbmobile#4]
It would be nice to have the Android release version available on F-Droid, too.

**Comment by v4rakh** [comment]
Hi. Feel free to progress there. :-)

**Comment by s4msung** [comment]
Sure, i already started looking into that.

Could you check the F-Droid inclusion policy https://f-droid.org/en/docs/Inclusion_Policy/ and see if there's any Issues with that? 

If that's fine I could either just open a Request for Packaging on their Issue tracker or contribute to their F-Droid Data repository.

**Comment by v4rakh** [comment]
The only point which might needs handling is to look into the bundling/dependencies which a default Android/Flutter project has and if we need to change some build mechanism or better add a new one for FDroid. To be honest, I don't have time to invest into another build mechanism, feel free to take a look please.

The rest of the document looks like fbmobile fulfills everything.

**Comment by v4rakh** [comment]
Hi @s4msung. This repository will be moved to a private hosted Git site. I would really appreciate your contributions though. Writing this because of the mail notification. See the issue here: https://git.myservermanager.com/varakh/fbmobile/issues/1
